export interface User { id:number; username:string; email:string; first_name:string; last_name:string; role:string; phone:string; avatar?:string; }
export interface Agency { id:number; name:string; owner:number; logo?:string; address:string; city:string; phone:string; email:string; website?:string; description:string; license_number:string; agents_count:number; is_active:boolean; created_at:string; }
export interface Agent { id:number; user:User; agency:number; agency_name:string; employee_id:string; specialization:string; commission_rate:string; is_active:boolean; }
export interface PropertyImage { id:number; image:string; caption:string; is_cover:boolean; order:number; }
export interface Property { id:number; title:string; description:string; property_type:string; offer_type:string; status:string; price:string; rent_price?:string; address:string; city:string; district:string; area:string; bedrooms:number; bathrooms:number; parking:boolean; garden:boolean; pool:boolean; security:boolean; furnished:boolean; is_featured:boolean; views_count:number; images:PropertyImage[]; agency_name:string; agent_name?:string; agency:number; agent?:number; created_at:string; }
export interface Client { id:number; first_name:string; last_name:string; email:string; phone:string; client_type:string; company_name?:string; agency:number; created_at:string; }
export interface Transaction { id:number; transaction_number:string; transaction_type:string; status:string; property:number; property_title:string; client:number; client_name:string; agent?:number; amount:string; commission:string; transaction_date:string; notes:string; created_at:string; }
export interface Contract { id:number; transaction:number; contract_type:string; status:string; contract_number:string; title:string; content:string; start_date:string; end_date?:string; signed_date?:string; created_at:string; }
export interface PaginatedResponse<T> { count:number; next?:string; previous?:string; results:T[]; }
